work_dir: ./work_dir/HumSk/xsub/dgnn_test
model_saved_name: ./runs/HumSk_cs_dgnn_test

# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  joint_data_path: ./data/HumanBody/xsub/val_joint.npy
  bone_data_path: ./data/HumanBody/xsub/val_bone.npy
  label_path: ./data/HumanBody/xsub/val_label.pkl
  debug: False

# model
model: model.dgnn.Model
model_args:
  num_class: 5
  num_point: 17
  num_person: 2
  graph: graph.HumSk.Graph

# test
phase: test
device: [0, 1]
test_batch_size: 10
# NOTE: default tests the newest weight
# Change filename if using different batch sizes
weights: ./runs/HumSk_dgnn-180-2240.pt
save_score: True
