work_dir: ./work_dir/HumSk/xsub/dgnn
model_saved_name: ./runs/HumSk_dgnn
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  joint_data_path: ./data/HumanBody/xsub/train_joint.npy
  bone_data_path: ./data/HumanBody/xsub/train_bone.npy
  label_path: ./data/HumanBody/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  joint_data_path: ./data/HumanBody/xsub/val_joint.npy
  bone_data_path: ./data/HumanBody/xsub/val_bone.npy
  label_path: ./data/HumanBody/xsub/val_label.pkl

# model
model: model.dgnn.Model
model_args:
  num_class: 5
  num_point: 17
  num_person: 2
  graph: graph.HumSk.Graph
  # graph_args:
  #   labeling_mode: 'spatial'

# optim
weight_decay: 0.0005
base_lr: 0.1
step: [60, 90]

# training
device: [0]
batch_size: 5
test_batch_size: 5
num_epoch: 180
nesterov: True
freeze_graph_until: 10  # Number of epochs until graphs can be updated

