base_lr: 0.1
batch_size: 5
config: ./config/Humen-skele/train.yaml
device:
- 0
eval_interval: 5
feeder: feeders.feeder.Feeder
freeze_graph_until: 10
ignore_weights: []
log_interval: 100
model: model.dgnn.Model
model_args:
  graph: graph.HumSk.Graph
  num_class: 5
  num_person: 2
  num_point: 17
model_saved_name: ./runs/HumSk_dgnn
nesterov: true
num_epoch: 120
num_worker: 8
optimizer: SGD
phase: train
print_log: true
save_interval: 2
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 60
- 90
test_batch_size: 5
test_feeder_args:
  bone_data_path: ./data/HumanBody/xsub/val_bone.npy
  joint_data_path: ./data/HumanBody/xsub/val_joint.npy
  label_path: ./data/HumanBody/xsub/val_label.pkl
train_feeder_args:
  bone_data_path: ./data/HumanBody/xsub/train_bone.npy
  debug: false
  joint_data_path: ./data/HumanBody/xsub/train_joint.npy
  label_path: ./data/HumanBody/xsub/train_label.pkl
  normalization: false
  random_choose: false
  random_move: false
  random_shift: false
  window_size: -1
weight_decay: 0.0005
weights: null
work_dir: ./work_dir/HumSk/xsub/dgnn
